name: MasterDeployCI
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'ethereum-basics.zip'
        exclusions: '*.git*'
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        files: |
          ethereum-basics.zip
